### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ygongdev** [ygongdev/ember-partial-codemod#1]
- [ ] Make sure `getAttributes` works correctly by aggressively testing it via unit tests.
- [x] Build a dependency graph of `partials`
- [x] Implement method that given the `module`, return the physical disk location. This has purpose for gathering `attributes` and performing `transform` via `ember-template-recast`.
